image: debian:buster-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - mkdir public
  - cp scripts/ciberlite-convergent-validity.html public/index.html
  - ls public
  artifacts:
    paths:
    - public
  only:
  - master
